[pytest]
pythonpath = src tests
filterwarnings =
    ignore::DeprecationWarning
    ignore::UserWarning
asyncio_mode = auto

[coverage:run]
omit =
    src/main.py
    src/swagger_config.py
    src/db/dynamodb_client.py 
    src/routes/__init__.py
    src/domain/models/__init__.py
    src/domain/calculators/monetary_calculations.py 
    src/exceptions/__init__.py
    src/exceptions/error_handler.py 
    src/marshallers/exporters/__init__.py
    src/marshallers/parsers/__init__.py
    src/repositories/__init__.py
    src/services/__init__.py
    src/utils/__init__.py
    src/validators/__init__.py
    src/routes/auth_routes.py                                         
    src/routes/health_check_routes.py
    src/routes/invoice_routes.py
    src/routes/user_routes.py
    src/utils/invoice_calculations.py
